language: go
go:
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr -u hacdias -t $GITHUB_TOKEN --replace --prerelease pre-release dist/
